export default [
	{
		"name":"口服液",
		"title":{
			"title1":"口服液",
			"title2":"让营养更美味",
			"title3":"上千种配方，多种剂型，专业质量控制，产品涵盖各种热门营养领域，让饮品营养美味。"
		},
		"bannerimg":"static/images/kouf-banner.jpg",
		"imgs":[
			"static/images/kouf-img1.jpg",
			"static/images/kouf-img1.jpg",
			"static/images/kouf-img1.jpg"
		],
		"textlist":[
			{
				"h2text":"全进口自动化生产设备",
				"ptext":"1000多种成熟饮品配方储备"
			},
			{
				"h2text":"系统监控，质量保障",
				"ptext":"产品覆盖热门营养领域，满足多种消费需求"
			},
			{
				"h2text":"玻璃瓶装、独立袋装多种剂型",
				"ptext":"时尚与健康结合，为产品差异化助力"
			}
		]
	},
	{
		"name":"粉剂",
		"title":{
			"title1":"粉剂",
			"title2":"专业、效率、稳定",
			"title3":"菌钥创新配方技术与强大供应链为您提供多种包装和类型，满足您的各种需求。"
		},
		"bannerimg":"static/images/fenj-banner.jpg",
		"imgs":[
			"static/images/fenj-img1.jpg",
			"static/images/fenj-img1.jpg",
			"static/images/fenj-img1.jpg"
		],
		"textlist":[
			{
				"h2text":"益生菌粉",
			},
			{
				"h2text":"蛋白质粉",
			},
			{
				"h2text":"胶原蛋白粉",
			},
			{
				"h2text":"果蔬纤维粉",
			},
			{
				"h2text":"代餐粉",
			},
			{
				"h2text":"DHA钙粉等",
			},
			{
				"h2text":"直饮型固体饮料系列（蔓越莓、针叶樱桃等）",
			}
		]
	},
	{
		"name":"凝胶糖果",
		"title":{
			"title1":"凝胶糖果",
			"title2":"专业团队，为产品质量保驾护航",
			"title3":"菌钥拥有国内前沿的研发中心，目前凝胶糖果产能达到100万/天，为您提供创新高效的产品服务。"
		},
		"bannerimg":"static/images/ningj-banner.jpg",
		"imgs":[
			"static/images/ningj-img1.jpg",
			"static/images/ningj-img1.jpg",
			"static/images/ningj-img1.jpg"
		],
		"textlist":[
			{
				"h2text":"专业化产品解决方案",
			},
			{
				"h2text":"力求将每一粒凝胶糖果的品质做到极致",
			},
			{
				"h2text":"引领营养科技，为健康增值",
			},
		]
	},
	{
		"name":"压片糖果",
		"title":{
			"title1":"压片糖果",
			"title2":"多样化的片剂产品解决方案，满足您的需求",
			"title3":"菌钥大健康的压片糖果符合GMP车间生产标准，我们力求将每一粒压片糖果的品质做到极致。"
		},
		"bannerimg":"static/images/yap-banner.jpg",
		"imgs":[
			"static/images/yap-img1.jpg",
			"static/images/yap-img1.jpg",
			"static/images/yap-img1.jpg"
		],
		"textlist":[
			{
				"h2text":"涵盖市面上热门产品",
			},
			{
				"h2text":"流化床自动造粒 先进工艺",
			},
			{
				"h2text":"物料传递 符合现代工学",
			},
			{
				"h2text":"层层把控 质量保障",
			},
		]
	},
	{
		"name":"滋养膏滋",
		"title":{
			"title1":"滋养膏滋",
			"title2":"用天然守护您的健康",
			"title3":"菌钥大健康健康以市场为导向，拥有专业的配方设计能力以及先进的生产与工艺，致力于为您提供健康营养的膏滋类产品。"
		},
		"bannerimg":"static/images/ziy-banner.jpg",
		"imgs":[
			"static/images/ziy-img1.jpg",
			"static/images/ziy-img1.jpg",
			"static/images/ziy-img1.jpg"
		],
		"textlist":[
			{
				"h2text":"成熟配方 高效滋补",
			},
			{
				"h2text":"风味改善 体验升级",
			},
			{
				"h2text":"有效吸收 营养升级",
			},
		]
	},
	{
		"name":"硬胶囊",
		"title":{
			"title1":"硬胶囊",
			"title2":"科学祖方，中西结合，给您的产品极致体验",
			"title3":"我们的生产线已达到600万/天，从研发到生产，满足您对硬胶囊的各种需求。"
		},
		"bannerimg":"static/images/yingj-banner.jpg",
		"imgs":[
			"static/images/yingj-img1.jpg",
			"static/images/yingj-img1.jpg",
			"static/images/yingj-img1.jpg"
		],
		"textlist":[
			{
				"h2text":"全进口自动化生产设备",
				"ptext":"1000多种成熟饮品配方储备"
			},
			{
				"h2text":"系统监控，质量保障",
				"ptext":"产品覆盖热门营养领域，满足多种消费需求"
			},
			{
				"h2text":"玻璃瓶装、独立袋装多种剂型",
				"ptext":"时尚与健康结合，为产品差异化助力"
			},
		]
	},
	{
		"name":"营养果冻",
		"title":{
			"title1":"营养果冻",
			"title2":"极具发展前景的剂型之一",
			"title3":"当营养注入零食，美味与健康碰撞，风靡功能性食品市场。"
		},
		"bannerimg":"static/images/yingy-banner.jpg",
		"imgs":[
			"static/images/yingy-img1.jpg",
			"static/images/yingy-img1.jpg",
			"static/images/yingy-img1.jpg"
		],
		"textlist":[
			{
				"h2text":"营养、美味兼具",
			},
			{
				"h2text":"风趣、风味并驱",
			},
			{
				"h2text":"多种口感、多重体验",
			},
		]
	},
]

